name: Automatic tests and code-coverage
on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Run unit tests and code-coverage
        run: |
          go test -race -covermode=atomic ./...